version: 0.0
os: linux
files: 
  - source: /
    destination: /home/ec2-user/flaskapp


hooks:
  BeforeInstall:
    - location: scripts/Install_dependensies.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_flask.sh
      timeout: 300
      runas: ec2-user